spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/master
    driverClassName: org.postgresql.Driver
    username: postgres
    password: P@ssw0rd

#tenants:
#  datasources:
#    vw:
#      url: jdbc:postgresql://localhost:5432/vw
#      driverClassName: org.postgresql.Driver
#      username: postgres
#      password: P@ssw0rd
#    bmw:
#      url: jdbc:postgresql://localhost:5432/bmw
#      driverClassName: org.postgresql.Driver
#      username: postgres
#      password: P@ssw0rd

#tenants.datasources.vw.url: jdbc:postgresql://localhost:5432/vw
#tenants.datasources.vw.driverClassName: org.postgresql.Driver
#tenants.datasources.vw.username: postgres
#tenants.datasources.vw.password: P@ssw0rd

#tenants.datasources.bmw.url: jdbc:postgresql://localhost:5432/bmw
#tenants.datasources.bmw.driverClassName: org.postgresql.Driver
#tenants.datasources.bmw.username: postgres
#tenants.datasources.bmw.password: P@ssw0rd
